export const RETRIEVE_MOVIES_GENRES_SUCCESS = 'RETRIEVE_MOVIES_GENRES_SUCCESS';

export const RETRIEVE_POPULAR_MOVIES_SUCCESS = 'RETRIEVE_POPULAR_MOVIES_SUCCESS';
export const RETRIEVE_TOPRATED_MOVIES_SUCCESS = 'RETRIEVE_TOPRATED_MOVIES_SUCCESS';
export const RETRIEVE_UPCOMING_MOVIES_SUCCESS = 'RETRIEVE_UPCOMING_MOVIES_SUCCESS';
export const RETRIEVE_NOWPLAYING_MOVIES_SUCCESS = 'RETRIEVE_NOWPLAYING_MOVIES_SUCCESS';

export const RETRIEVE_MOVIES_LIST_SUCCESS = 'RETRIEVE_MOVIES_LIST_SUCCESS';
